//
//  MapReviewCard.swift
//  Daydream
//
//  Created by Raymond Kim on 5/23/20.
//  Copyright © 2020 Raymond Kim. All rights reserved.
//

import UIKit
import SnapKit
import GooglePlacesSwift

final class MapReviewCard: UIView {

    static let height: CGFloat = 160

    // Cannot have rounded corners and drop shadow in same view layer
    private lazy var containerView: UIView = {
        let view = UIView()
        view.backgroundColor = .white
        view.addRoundedCorners(radius: 16)
        return view
    }()

    private lazy var authorLabel: UILabel = {
        let label = UILabel()
        label.text = "Author"
        label.font = .preferredFont(forTextStyle: .headline)
        label.textColor = .black
        label.adjustsFontSizeToFitWidth = true
        label.minimumScaleFactor = 0.7
        return label
    }()

    private lazy var authorImageView: UIImageView = {
        let imageView = UIImageView()
        return imageView
    }()

    private lazy var reviewLabel: UILabel = {
        let label = UILabel()
        label.font = .preferredFont(forTextStyle: .footnote)
        label.textColor = .black
        label.numberOfLines = 0
        label.minimumScaleFactor = 0.8
        return label
    }()

    private lazy var starsView: UIStackView = {
        let view = UIStackView()
        view.axis = .horizontal
        return view
    }()

    private lazy var star1ImageView: UIImageView = {
        let imageView = UIImageView()
        return imageView
    }()

    private lazy var star2ImageView: UIImageView = {
        let imageView = UIImageView()
        return imageView
    }()

    private lazy var star3ImageView: UIImageView = {
        let imageView = UIImageView()
        return imageView
    }()

    private lazy var star4ImageView: UIImageView = {
        let imageView = UIImageView()
        return imageView
    }()

    private lazy var star5ImageView: UIImageView = {
        let imageView = UIImageView()
        return imageView
    }()
    
    /// Only appears for review summaries generated by Gemini
    private lazy var attributionLabel: UILabel = {
        let label = UILabel()
        if let descriptor = UIFont.preferredFont(forTextStyle: .caption1).fontDescriptor.withSymbolicTraits(.traitItalic) {
            label.font = UIFont(descriptor: descriptor, size: 0)
        }
        label.textColor = .black
        label.textAlignment = .right
        return label
    }()

    override init(frame: CGRect) {
        super.init(frame: frame)
        backgroundColor = .clear
        addShadow(opacity: 0.6, offset: CGSize(width: 0, height: 1), radius: 2)
        addSubview(containerView)

        containerView.addSubview(authorLabel)
        containerView.addSubview(authorImageView)
        containerView.addSubview(reviewLabel)
        containerView.addSubview(starsView)
        starsView.addArrangedSubview(star1ImageView)
        starsView.addArrangedSubview(star2ImageView)
        starsView.addArrangedSubview(star3ImageView)
        starsView.addArrangedSubview(star4ImageView)
        starsView.addArrangedSubview(star5ImageView)

        containerView.snp.makeConstraints { make in
            make.edges.equalToSuperview()
        }

        authorImageView.snp.makeConstraints { make in
            make.leading.top.equalToSuperview().inset(16)
            make.size.equalTo(36)
        }

        authorLabel.snp.makeConstraints { make in
            make.leading.equalTo(authorImageView.snp.trailing).offset(8)
            make.centerY.equalTo(authorImageView.snp.centerY)
        }

        reviewLabel.snp.makeConstraints { make in
            make.leading.bottom.trailing.equalToSuperview().inset(16)
            make.top.equalTo(authorImageView.snp.bottom).offset(6)
        }

        starsView.snp.makeConstraints { make in
            make.leading.equalTo(authorLabel.snp.trailing).offset(4)
            make.trailing.equalToSuperview().inset(16)
            make.centerY.equalTo(authorImageView.snp.centerY)
        }

        [star1ImageView, star2ImageView, star3ImageView, star4ImageView, star5ImageView].forEach { imageView in
            imageView.snp.makeConstraints { make in
                make.size.equalTo(20)
            }
        }
    }

    func configure(_ review: GooglePlacesSwift.Review) {
        authorLabel.text = review.authorAttribution?.displayName
        reviewLabel.text = review.text
        updateStars(rating: review.rating)
        authorImageView.image = nil

        guard let profileUrl = review.authorAttribution?.photoUrl else {
            return
        }
        
        Task {
            do {
                let image = try await API.Image.loadImage(url: profileUrl)
                await MainActor.run {
                    authorImageView.image = image
                }
            } catch {}
        }
    }
    
    func configureWithSummary(_ summary: ReviewSummary) {
        reviewLabel.text = summary.text
        
        authorLabel.isHidden = true
        authorImageView.isHidden = true
        starsView.isHidden = true
        
        attributionLabel.text = summary.disclosureText
        containerView.addSubview(attributionLabel)
        
        reviewLabel.snp.remakeConstraints { make in
            make.leading.top.trailing.equalToSuperview().inset(16)
        }
        
        attributionLabel.snp.makeConstraints { make in
            make.top.equalTo(reviewLabel.snp.bottom).offset(4)
            make.leading.trailing.equalToSuperview().inset(16)
            make.bottom.equalToSuperview().inset(8)
        }
    }

    private func updateStars(rating: Float) {
        guard rating >= 0 && rating <= 5 else {
            return
        }

        let starImageViews = [star1ImageView, star2ImageView, star3ImageView, star4ImageView, star5ImageView]
        for i in 1..<6 {
            if Float(i) <= rating {
                starImageViews[i-1].image = UIImage(systemName: "star.fill")
                starImageViews[i-1].tintColor = .systemYellow
            } else {
                starImageViews[i-1].image = UIImage(systemName: "star")
                starImageViews[i-1].tintColor = .lightGray
            }
        }
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}
