# The Deliverfile allows you to store various iTunes Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

automatic_release(true)
phased_release(false)
reset_ratings(false)