# The Deliverfile allows you to store various iTunes Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

release_notes({
    'default' => "Performance improvements and bug fixes"
})
automatic_release(true)
submission_information({
    add_id_info_uses_idfa: false
})