# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.68.2"

default_platform :ios
xcversion(version: "11.4.1")

platform :ios do
  before_all do
    # cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    run_tests
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    build_app # more options available
    upload_to_testflight

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  # desc "Deploy a new version to the App Store"
  # lane :release do
  #   # sync_code_signing(type: "appstore")
  #   capture_screenshots
  #   increment_build_number(
  #     build_number: app_store_build_number + 1,
  #     xcodeproj: "Daydream.xcodeproj"
  #   )
  #   increment_version_number
  #   build_app(scheme: "Daydream") # Build your app - more options available
  #   upload_to_app_store(force: true)
  #   # frame_screenshots
  # end

   desc "Deploy a new major version to the App Store (major functionality with potential breaking changes)"
  lane :release_new_major_version do
    # sync_code_signing(type: "appstore")
    capture_screenshots
    increment_build_number(
      build_number: app_store_build_number + 1,
      xcodeproj: "Daydream.xcodeproj"
    )
    increment_version_number(
    	bump_type: "major"
    )
    build_app(scheme: "Daydream") # Build your app - more options available
    upload_to_app_store(force: true)
    # frame_screenshots
  end

  desc "Deploy a new minor version to the App Store (minor functionality with backwards compatibility)"
  lane :release_new_minor_version do
    # sync_code_signing(type: "appstore")
    # capture_screenshots
    increment_build_number(
      build_number: 1,
      xcodeproj: "Daydream.xcodeproj"
    )
    increment_version_number(
    	bump_type: "minor"
    )
    build_app(scheme: "Daydream") # Build your app - more options available
    upload_to_app_store(force: true)
  end

    desc "Deploy a new patch version to the App Store (bug fixes with backwards compatibility)"
  lane :release_new_patch_version do
    # sync_code_signing(type: "appstore")
    capture_screenshots
    increment_build_number(
      build_number: app_store_build_number + 1,
      xcodeproj: "Daydream.xcodeproj"
    )
    increment_version_number(
    	bump_type: "patch"
    )
    build_app(scheme: "Daydream") # Build your app - more options available
    upload_to_app_store(force: true)
    # frame_screenshots
  end

  desc "Deploy a new build only to the App Store; no version changes"
  lane :release_new_build_only do
    # sync_code_signing(type: "appstore")
    # capture_screenshots
    increment_build_number(
      build_number: app_store_build_number + 1,
      xcodeproj: "Daydream.xcodeproj"
    )
    build_app(scheme: "Daydream") # Build your app - more options available
    upload_to_app_store(force: true)
  end

  desc "Generate screenshots with custom settings"
  lane :screenshots do
    capture_screenshots(stop_after_first_error: true)
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics
